### ISSUE TITLE
Aligning results with ORT results: add support for metadata

### ISSUE THREAD

**Issue by TG1999** [nexB/nuget-inspector#2]
[analyzer-result.yml.txt](https://github.com/nexB/nuget-inspector/files/10087190/analyzer-result.yml.txt) - ort results
[nuget-inpector-results.json.txt](https://github.com/nexB/nuget-inspector/files/10087192/nuget-inpector-results.json.txt) - nuget inspector results

**Comment by TG1999** [comment]
I had one observation that multiple versions were reported for a single package by ort.
For example:
```NuGet::runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl:4.3.0
NuGet::runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl:4.3.2```

**Comment by pombredanne** [comment]
We now fetch metadata... @TG1999 is there still duplication?
NuGet/MSBuild cannot handle multiple versions of the same library for a given project AFAIK, so IMHO whatever ORT was returning before was likely incorrect.

**Comment by nnobelis** [comment]
Review with version 0.7.2.

I used an ORT example Nuget project to test the nuget-inspector: https://github.com/oss-review-toolkit/ort/tree/main/analyzer/src/funTest/assets/projects/synthetic/nuget
And run the nuget-inspector in Debian Bullseye with:
```
❯ ~/bin/nuget-inspector/nuget-inspector –verbose --project-file ~/IdeaProjects/OSMI/oss-review-toolkit-internal/analyzer/src/funTest/assets/projects/synthetic/nuget/packages.config --nuget-config ~/IdeaProjects/OSMI/oss-review-toolkit-internal/analyzer/src/funTest/assets/projects/synthetic/nuget/nuget.config --json /home/nino/nuget-inspector-result2.json
```

The metadata has improved (for instance the declared license is now present in the result). However, I noticed some information are still missing, for instance Project2: Webgrease 1.5.2 is missing the following metadata that ORT returns:

![image](https://user-images.githubusercontent.com/66427221/213138105-562d0c0a-88b7-45cd-a86c-2862605b375b.png)

**Comment by pombredanne** [comment]
The latest v0.9.1 has all details now. This is much slower though. Closing!
