### ISSUE TITLE
nuget-inspector command is not working in windows OS

### ISSUE THREAD

**Issue by JacinthaThompson** [nexB/nuget-inspector#45]
I am trying to run the command in windows OS and getting below error message.
Please assist me.
"nuget-inspector --help"
nuget-inspector: The term 'nuget-inspector' is not recognized as a name of a cmdlet, function, script file, 
or executable program.
Thanks,
Jacintha

**Comment by pombredanne** [comment]
@JacinthaThompson how did you install the tool?
did you "cd" to the directory where this is extracted?

**Comment by JacinthaThompson** [comment]
Yes. I have tried in below location.
c:/nuget-inspector> nuget-inspector --help

The nuget-inspector folder contains the inspector project files.

**Comment by JacinthaThompson** [comment]
I have followed the below steps
1. Install the dotnet SDK 6.x for your platform from Microsoft https://learn.microsoft.com/en-us/dotnet/core/install/

2.Download and extract the pre-built binary release archive from the release page https://github.com/nexB/nuget-inspector for your operating system. (Linux-only for now)

3. Run the command line utility with:
nuget-inspector --help

**Comment by pombredanne** [comment]
Can you run a "dir" command in the c:/nuget-inspector directory and past the results here?
Also, which version of Windows and which processor architecture do you use?

**Comment by pombredanne** [comment]
@JacinthaThompson It looks like you are using a github clone or source archive. If that's what you really want you would need to compile the sources.
I am not sure this is what you want. Instead get the pre-built archive for Windows from the latest release tag https://github.com/nexB/nuget-inspector/releases/tag/v0.9.12

This would be this:
https://github.com/nexB/nuget-inspector/releases/download/v0.9.12/nuget-inspector-v0.9.12-win-x64.tar.gz

**Comment by JacinthaThompson** [comment]
Yes I have tried with git clone before and tried to follow the steps in readme file.
Thank you for sharing above details. I will use the pre-built archive for Windows and try to run the commands.

**Comment by JacinthaThompson** [comment]
Thank you for your help.
I am able to generate the Json output file with packages dependencies.

**Comment by pombredanne** [comment]
@JacinthaThompson great! Please report your issues and questions (and successes too!)
You are welcomed to close this now too.
